### ISSUE TITLE
Server - Client actual hearts not syncing

### ISSUE THREAD

**Issue by Thyriel** [TechnikforLife/FirstAid#1]
In Singleplayer this worked correctly so i guess it's a problem between server-client sync:
When hearts get regenerated (either if through bandages or eating) most times they stay damaged on the client but seem to regenerate. This is especially seeable when hunger regen is enabled but the hunger bar stops moving down while hearts are still not full. (Hearts are full but shown as damaged)
Reconnecting to server and hearts are instantly full again.

Forge: 14.23.0.2501
FirstAid 1.2.3

**Comment by ichttt** [comment]
It might be because of a config desync, did your server have the same config options as the client?

**Comment by Thyriel** [comment]
Yes both same configs.
I will test tomorrow a bit more, after a quick test it either seems to have to do with food regen being enabled or higher hearts configured then your default values. At least with default configs the problem doesn't seem to appear. (Although i had it one time so far with default config that the bandage window shows a heart less on left leg then the upper left UI)

**Comment by ichttt** [comment]
Yeah, I think I need to rewrite the entire rendering code, there are many things that are playing not as nice as I would like them to. Looking into the other issue right now

**Comment by Thyriel** [comment]
Btw something else i noticed while increasing the hearts per body part: Falling damage doesn't seem to scale with increased hearts. When i just have like 1/3rd more hearts your already almost unkillable by falling damage, even from great heights.
